### ISSUE TITLE
Create function replicating behaviour of Update function?

### ISSUE THREAD

**Issue by nooproblem** [gernest/nutz#3]
Hi,

To start, I would just like to say that nutz is a great piece of abstraction from boltdb!

However, I just have a small question about the Create function. The following example is modified from the how to use section:

``` go
package main

import (
    "fmt"

    "github.com/gernest/nutz"
)

func main() {

    databaseName := "bolt.db"

    db := nutz.NewStorage(databaseName, 0600, nil)

    /* 
    - city
        - school
            - class
                - teacher
                    "john Doe": "scientist"
    */

    db.Create("city", "john Doe", []byte("scientist"), "school", "class", "teacher")

    jDs := db.Get("city", "john Doe", "school", "class", "teacher")

    if jDs.Error != nil {
        fmt.Println(jDs.Error)
    } else {
        fmt.Println("john Doe", string(jDs.Data)) // => john Doe scientist
    }

    /*-----------------------*/ 

    db.Create("city", "john Doe", []byte("mathematician"), "school", "class", "teacher")

    jDm := db.Get("city", "john Doe", "school", "class", "teacher")

    if jDm.Error != nil {
        fmt.Println(jDm.Error)
    } else {
        fmt.Println("john Doe", string(jDm.Data)) // => john Doe scientist
    }

    db.DeleteDatabase()
}
```

Firstly, a nested bucket is created with the key "john Doe" with the value "scientist". Then a nested bucket is created with the same key but the value "mathematician". You would have expected nutz to return an error because the key already exists and therefore it could not create a new nested bucket. However, the Create function overrides the nested bucket with the key "john Doe" with the value "scientist". Is this behaviour not overlapping with the Update function? If the Create function returned an error when trying to create a bucket with a key that already exists then all that is required to change the value is a simple switch to using the Update function instead. This would more logical and introduce better data consistency in my honest opinion.

Your thoughts / advice will be greatly appreciated.

**Comment by gernest** [comment]
@nooproblem thanks for poking around `nutz` . Your observation is correct, however let us look at how the nested buckets are created reference [here](https://github.com/gernest/nutz/blob/17bfec3e80cc79b4488b881805247d075672cd33/nutz.go#L316)

This is function responsible for creating the nested buckets, and in our case it should be the one to complain about already existing bucket key right?

``` go
func createNestedBuckets(n []string, b *bolt.Bucket) (*bolt.Bucket, error) {
    var prev *bolt.Bucket
    var uerr error
    prev = b
    for i := 0; i < len(n); i++ {
        curr, err := prev.CreateBucketIfNotExists([]byte(n[i]))
        if err != nil {
            uerr = err
            break
        }
        prev = curr
    }
    return prev, uerr
}
```

Notice that, I use the `CreateBucketIfNotExists` method which doesn't indeed cosider when the key is already there  reference [here](https://github.com/boltdb/bolt/blob/51f99c862475898df9773747d3accd05a7ca33c1/bucket.go#L195)

So, how about you help me modifying the function so as we can attain the desired functionality?. You dug this out and I think you deserve credit( If you don't mind, I willl give hints below)

The first suggestion that I can think of is to check if the bucket already exist before creating one. What I know is if you return an error it will be taken care of without any problem.

so something linke below,please see the comments in the code.

``` go
func createNestedBuckets(n []string, b *bolt.Bucket) (*bolt.Bucket, error) {
    var prev *bolt.Bucket
    var uerr error
    prev = b
    for i := 0; i < len(n); i++ {

        // This is pseudo code, hope it helps
        //
        //      if The Bucket Exist {
        //          uerr= PUT THE BUCKET EXIST ERROR
        //          break
        //      }

        curr, err := prev.CreateBucketIfNotExists([]byte(n[i]))
        if err != nil {
            uerr = err
            break
        }
        prev = curr
    }
    return prev, uerr
}
```

The second suggestion is to use `prev.CreateBucket` see the reference to the bold method [here](https://github.com/boltdb/bolt/blob/51f99c862475898df9773747d3accd05a7ca33c1/bucket.go#L151) 

As you can see the second one is the most obvious, and we will let bolt take care of the process to check the bucket exist or not( I give it a +1)

 You are offcourse free to pull out any optimal solution, and we will check it out before I merge it.

NB: I wrote thiis a while ago, and I can see there is a lot of room for improvement.
